version: "3.9"
services:
  postgresql:
    image: postgres
    hostname: "${POSTGRES_HOSTNAME}"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"

